export const dropdownData = [
  {label: 'Buscar por nombre y apellido', value: '1'},
  {label: 'Buscar por fecha de nacimiento', value: '2'},
  {label: 'Buscar por número de teléfono', value: '3'},
  {label: 'Buscar por departamento', value: '4'},
  {label: 'Buscar por dirección', value: '5'},
  {label: 'Buscar por profesión', value: '6'},
  {label: 'Buscar por ingresos', value: '7'},
];

export const usersData = [
  {
    firstName: 'Ana',
    lastName: 'Amaya',
    birthday: '21/12/1981',
    gender: 'Femenino',
    cellphone: '011789345121',
    city: 'San Salvador',
    address: 'Colonia medica casa 23',
    profession: 'Enfermera',
    incomes: 875,
  },
  {
    firstName: 'Elsy',
    lastName: 'Merino',
    birthday: '17/12/1977',
    gender: 'Femenino',
    cellphone: '01178434522',
    city: 'Santa tecla',
    address: 'ciudad Merliot residencial los cipreses casa 11',
    profession: 'Ama de casa',
    incomes: 775,
  },
  {
    firstName: 'Marina',
    lastName: 'Caceres',
    birthday: '23/12/1986',
    gender: 'Femenino',
    cellphone: '01178934533',
    city: 'San Vicente',
    address: 'cantón tepitetan barrio san jose casa 1',
    profession: 'Doctora',
    incomes: 1875,
  },
  {
    firstName: 'Santiago',
    lastName: 'Sanchez',
    birthday: '11/12/1977',
    gender: 'Masculino',
    cellphone: '01178934379',
    city: 'La Paz',
    address: 'Zacatecoluca colonia san jose casa 23',
    profession: 'Agricultor',
    incomes: 575,
  },
  {
    firstName: 'Marvin',
    lastName: 'Arevalo',
    birthday: '17/12/1977',
    gender: 'Masculino',
    cellphone: '01178934320',
    city: 'San Salvador',
    address: 'colina cuscatlan casa 44',
    profession: 'Enfermero',
    incomes: 899,
  },
  {
    firstName: 'Luis',
    lastName: 'Carcamo',
    birthday: '01/12/1977',
    gender: 'Masculino',
    cellphone: '0117890117934321',
    city: 'San Salvador',
    address: 'colina ',
    profession: 'Enfermero',
    incomes: 899,
  },
];
